2025-05-27 08:26:17.586 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:26:17.590 [info] [Error - 8:26:17] Server initialization failed.
2025-05-27 08:26:17.591 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:17.591 [info] [Info  - 8:26:17] Connection to server got closed. Server will restart.
2025-05-27 08:26:17.591 [info] true
2025-05-27 08:26:17.591 [info] [Error - 8:26:17] Python Jedi client: couldn't create connection to server.
2025-05-27 08:26:17.591 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:17.600 [info] [Error - 8:26:17] Server process exited with code 1.
2025-05-27 08:26:17.696 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:26:17.696 [info] [Error - 8:26:17] Server process exited with code 1.
2025-05-27 08:26:17.697 [info] [Error - 8:26:17] Server initialization failed.
2025-05-27 08:26:17.697 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:17.697 [info] [Info  - 8:26:17] Connection to server got closed. Server will restart.
2025-05-27 08:26:17.697 [info] true
2025-05-27 08:26:17.697 [info] [Error - 8:26:17] Python Jedi client: couldn't create connection to server.
2025-05-27 08:26:17.697 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:17.894 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:26:17.894 [info] [Error - 8:26:17] Server process exited with code 1.
2025-05-27 08:26:17.921 [info] [Error - 8:26:17] Server initialization failed.
2025-05-27 08:26:17.921 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:17.921 [info] [Info  - 8:26:17] Connection to server got closed. Server will restart.
2025-05-27 08:26:17.921 [info] true
2025-05-27 08:26:17.921 [info] [Error - 8:26:17] Python Jedi client: couldn't create connection to server.
2025-05-27 08:26:17.921 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:17.921 [info] [Error - 8:26:17] Restarting server failed
2025-05-27 08:26:17.921 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:18.026 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:26:18.028 [info] [Error - 8:26:18] Server initialization failed.
2025-05-27 08:26:18.028 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:18.028 [info] [Info  - 8:26:18] Connection to server got closed. Server will restart.
2025-05-27 08:26:18.028 [info] true
2025-05-27 08:26:18.028 [info] [Error - 8:26:18] Python Jedi client: couldn't create connection to server.
2025-05-27 08:26:18.028 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:18.028 [info] [Error - 8:26:18] Restarting server failed
2025-05-27 08:26:18.028 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:18.032 [info] [Error - 8:26:18] Server process exited with code 1.
2025-05-27 08:26:18.087 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:26:18.091 [info] [Error - 8:26:18] Server initialization failed.
2025-05-27 08:26:18.091 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:18.091 [info] [Error - 8:26:18] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2025-05-27 08:26:18.091 [info] [Error - 8:26:18] Python Jedi client: couldn't create connection to server.
2025-05-27 08:26:18.091 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:18.091 [info] [Error - 8:26:18] Restarting server failed
2025-05-27 08:26:18.091 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:26:18.092 [info] [Error - 8:26:18] Server process exited with code 1.
2025-05-27 08:39:20.910 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:39:20.910 [info] [Error - 8:39:20] Server process exited with code 1.
2025-05-27 08:39:20.916 [info] [Error - 8:39:20] Server initialization failed.
2025-05-27 08:39:20.916 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:39:20.916 [info] [Info  - 8:39:20] Connection to server got closed. Server will restart.
2025-05-27 08:39:20.916 [info] true
2025-05-27 08:39:20.916 [info] [Error - 8:39:20] Python Jedi client: couldn't create connection to server.
2025-05-27 08:39:20.916 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:39:21.039 [info] [Error - 8:39:21] Client Python Jedi: connection to server is erroring.
write EPIPE
Shutting down server.
2025-05-27 08:39:21.040 [info] [Error - 8:39:21] Stopping server failed
2025-05-27 08:39:21.040 [info] Error: Client is not running and can't be stopped. It's current state is: startFailed
    at P.shutdown (c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\out\client\extension.js:2:2026065)
    at P.shutdown (c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\out\client\extension.js:2:2229122)
    at P.stop (c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\out\client\extension.js:2:2025637)
    at P.handleConnectionError (c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\out\client\extension.js:2:2032383)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-05-27 08:39:21.040 [info] [Error - 8:39:21] Server initialization failed.
2025-05-27 08:39:21.040 [info]   Message: write EPIPE
  Code: -32099 
2025-05-27 08:39:21.040 [info] [Error - 8:39:21] Python Jedi client: couldn't create connection to server.
2025-05-27 08:39:21.040 [info]   Message: write EPIPE
  Code: -32099 
2025-05-27 08:39:21.041 [info] [Error - 8:39:21] Restarting server failed
2025-05-27 08:39:21.041 [info]   Message: write EPIPE
  Code: -32099 
2025-05-27 08:39:21.043 [info] [Info  - 8:39:21] Connection to server got closed. Server will restart.
2025-05-27 08:39:21.043 [info] true
2025-05-27 08:39:21.080 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:39:21.080 [info] [Error - 8:39:21] Server process exited with code 1.
2025-05-27 08:39:21.174 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:39:21.174 [info] [Error - 8:39:21] Server process exited with code 1.
2025-05-27 08:39:21.181 [info] [Error - 8:39:21] Server initialization failed.
2025-05-27 08:39:21.181 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:39:21.181 [info] [Info  - 8:39:21] Connection to server got closed. Server will restart.
2025-05-27 08:39:21.181 [info] true
2025-05-27 08:39:21.182 [info] [Error - 8:39:21] Python Jedi client: couldn't create connection to server.
2025-05-27 08:39:21.182 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:39:21.288 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:39:21.288 [info] [Error - 8:39:21] Server process exited with code 1.
2025-05-27 08:39:21.289 [info] [Error - 8:39:21] Server initialization failed.
2025-05-27 08:39:21.289 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:39:21.289 [info] [Info  - 8:39:21] Connection to server got closed. Server will restart.
2025-05-27 08:39:21.289 [info] true
2025-05-27 08:39:21.289 [info] [Error - 8:39:21] Python Jedi client: couldn't create connection to server.
2025-05-27 08:39:21.289 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:39:21.289 [info] [Error - 8:39:21] Restarting server failed
2025-05-27 08:39:21.289 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:39:21.355 [info] Traceback (most recent call last):
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\run-jedi-language-server.py", line 12, in <module>
    from jedi_language_server.cli import cli  # noqa: E402
  File "c:\Users\owner\.vscode\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi_language_server\__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

2025-05-27 08:39:21.356 [info] [Error - 8:39:21] Server process exited with code 1.
2025-05-27 08:39:21.356 [info] [Error - 8:39:21] Server initialization failed.
2025-05-27 08:39:21.356 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:39:21.356 [info] [Error - 8:39:21] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2025-05-27 08:39:21.356 [info] [Error - 8:39:21] Python Jedi client: couldn't create connection to server.
2025-05-27 08:39:21.356 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2025-05-27 08:39:21.356 [info] [Error - 8:39:21] Restarting server failed
2025-05-27 08:39:21.356 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
